# Generated by Django 4.0.3 on 2022-03-30 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('date', models.DateField(default=datetime.date(2022, 3, 30))),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
